service: aaronjayoliver-graphql-api
provider:
  name: aws
  region: eu-west-1
  runtime: nodejs20.x
  memorySize: 128
  timeout: 3
  httpApi:
    cors: true
functions:
  graphql:
    handler: src/index.handler
    events:
      - httpApi:
          path: /graphql
          method: POST
      - httpApi:
          path: /graphql
          method: GET
build:
  esbuild:
    minify: true
